[tool.pysen]
version = "0.9.1"

[tool.pysen-cli]
settings_dir = "."

[tool.pysen.lint]
enable_black = false
enable_flake8 = false
enable_isort = false
enable_mypy = false

[tool.pysen.lint.source]
includes = [
    "launcher.sh",
    "script.sh",
]

[tool.pysen.plugin.shellcheck]
function = "pysen_plugins::shellcheck"
